# Generated by Django 3.1.3 on 2020-11-19 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('teachers', models.TextField(default='[]', verbose_name='Преподаватели')),
                ('tasks', models.TextField(default='[]', verbose_name='Задания')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, verbose_name='Название')),
                ('method', models.CharField(choices=[('E', 'E'), ('W', 'W')], max_length=1, verbose_name='метод расчёта')),
                ('value', models.FloatField(verbose_name='Коэффициент')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentplanner.discipline', verbose_name='Дисциплина')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('disiplines', models.TextField(default='[]', verbose_name='Дисциплины')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('mark_numerator', models.IntegerField(null=True)),
                ('mark_denominator', models.IntegerField(null=True)),
                ('due_time', models.DateField(verbose_name='Сдать до')),
                ('priority', models.IntegerField(verbose_name='Приоритет')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено?')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentplanner.discipline', verbose_name='Дисциплина')),
                ('pass_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentplanner.teacher', verbose_name='Сдать')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('weight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentplanner.weight', verbose_name='Вес')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('disiplines', models.TextField(default='[]', verbose_name='Дисциплины')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='discipline',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentplanner.semester', verbose_name='Семестр'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
